### PR TITLE
support IE by using alternatives to String.includes(), String.trimLeft(), String.trimRight()

### PR DESCRIPTION
**Pull request by anne-gropler**
Maybe we want to support IE (maybe for pure nostalgia, or for our users with nostalgia).

See Issue #174 .

### CODE REVIEW

**Comment by bwasty** [comment]
Normally we add the necessary pollyfills to `source/polyfill.ts`. Though we have also discussed getting rid of that file and instead documenting which polyfill npm package to use in case IE support is needed.

**Comment by bwasty** [comment]
Additional note: we probably have duplicated polyfills in our 'application', since Angular also has/depends on some polyfills.

**Comment by anne-gropler** [comment]
Ok. so what should I do? Add that to `source/polyfill.ts` until you get rid of it?

**Comment by anne-gropler** [comment]
What am I missing here?
grafik

**Pull request merged**
