### PR TITLE
Environment rendering pass

### LINKED ISSUE #114: integrate common environment mapping techniques
based on the blog example that is already prepared and based on my master's thesis

### PR DESCRIPTION
**Pull request by p-otto**
This adds an `EnvironmentRenderingPass`, which renders four types of environment textures types via an ndc triangle.
includes #244, merge after that one
closes #114

### CODE REVIEW

**Comment by p-otto** [comment]
@cgcostume While working on this, I found out that we are handling cubemap faces in an incorrect way. The +x, -x, +z and -z faces have an inverted Y coordinate in comparison to the usual WebGL way of handling texture mapping: https://www.khronos.org/opengl/wiki/Cubemap_Texture#Upload_and_orientation

Currently we are implicitly flipping all faces in `TextureCube::fetch`, however this results in the wrong orientation in the X axis. To be correct, we would need to instead rotate all faces by 180°.
This is currently worked around in the envmapping example with a `ray.x *= -1.0`, but when implementing reflections using cubemaps this workaround is kind of counter intuitive.

One way to fix this is to perform the 180° rotation either in ERMT or during loading cubemaps in webgl-operate. How should we proceed here?

**Comment by cgcostume** [comment]
* ermt should **display** the textures as is now - so -x +z +x -z should always be visible like this.
* ermt should **export** the textures as described by khronos
* webgl-operate should **import** as is, since it's assumed to be already correct 
* our shaders used for **env mapping** should be adjusted/fixed accordingly

**Comment by cgcostume** [comment]
@p-otto what's your opinion on this?

**Comment by p-otto** [comment]
@cgcostume Sounds good, maybe we can later add an export option for ERMT to target either WebGL or other tools/APIs that use the conventional format.

**Pull request merged**
